//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvetMill
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPMPM
    {
        public int ID { get; set; }
        public Nullable<int> KEYF { get; set; }
        public Nullable<System.DateTime> DATAT { get; set; }
        public Nullable<int> TAKT { get; set; }
        public Nullable<int> IZM { get; set; }
        public Nullable<short> F1 { get; set; }
        public Nullable<short> F2 { get; set; }
        public Nullable<short> F3 { get; set; }
        public Nullable<short> F4 { get; set; }
        public Nullable<short> F5 { get; set; }
        public Nullable<short> F6 { get; set; }
        public Nullable<short> F7 { get; set; }
        public Nullable<short> F8 { get; set; }
        public Nullable<short> F9 { get; set; }
        public Nullable<short> F10 { get; set; }
        public Nullable<short> F11 { get; set; }
        public Nullable<short> F12 { get; set; }
        public Nullable<short> F13 { get; set; }
        public Nullable<short> F14 { get; set; }
        public Nullable<short> F15 { get; set; }
        public Nullable<short> F16 { get; set; }
        public Nullable<short> F17 { get; set; }
        public Nullable<short> F18 { get; set; }
        public Nullable<short> F19 { get; set; }
        public Nullable<short> F20 { get; set; }
        public Nullable<short> F21 { get; set; }
        public Nullable<short> F22 { get; set; }
        public Nullable<short> F23 { get; set; }
        public Nullable<short> F24 { get; set; }
        public Nullable<short> F25 { get; set; }
        public Nullable<short> NUMSAMPLE { get; set; }
    }
}
